spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/decidish
    username: user
    password: password
  jpa:
    hibernate:
      # Ensure a clean database for every test: drops and recreates schema
      ddl-auto: create-drop
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  application:
    name: "core"
  flyway:
    enabled: "false"
  ssl:
    bundle:
      pem:
        rewe-client:
          keystore:
            # You can set these defaults here, or override them via Docker Env Vars
            # The syntax ${ENV_VAR:default} works in YAML too.
            certificate: "${REWE_CERT_PATH:classpath:certificates/rewe.pem}"
            private-key: "${REWE_KEY_PATH:classpath:certificates/rewe.key}"