spring:
  application:
    name: "core"
  ssl:
    bundle:
      pem:
        rewe-client:
          keystore:
            # You can set these defaults here, or override them via Docker Env Vars
            # The syntax ${ENV_VAR:default} works in YAML too.
            certificate: "${REWE_CERT_PATH:classpath:certificates/rewe.pem}"
            private-key: "${REWE_KEY_PATH:classpath:certificates/rewe.key}"