services:
  # ----------------------------------------------------------------
  # Databases & Cache
  # ----------------------------------------------------------------

  # PostgreSQL with pgvector
  postgres:
    image: pgvector/pgvector:pg16
    container_name: dev_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: dev_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # ----------------------------------------------------------------
  # Application Services
  # ----------------------------------------------------------------

  # Core Server
  core-server:
    build: ./backend/core
    container_name: dev_java
    ports:
      - "8080:8080"
    volumes:
      - ./backend/core:/app
      - ~/.gradle:/home/gradle/.gradle
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  # Personalization Server
  personalization-server:
    build: ./backend/personalization
    container_name: dev_go
    ports:
      - "8082:8082"
    volumes:
      - ./backend/personalization:/app
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
    networks:
      - app-network

  # MLPipeline
  mlpipeline:
    build: ./mlpipeline
    container_name: dev_python
    ports:
      - "8000:8000"
    volumes:
      - ./mlpipeline:/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - app-network

  # Client: React Native Web
  client:
    build: ./client
    container_name: dev_client
    ports:
      - "8081:8081"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - API_JAVA=http://core-server:8080
      - API_GO=http://personalization-server:8082
      - API_PYTHON=http://mlpipeline:8000
#    depends_on:
#      - core
#      - personalization
#      - mlpipeline
    networks:
      - app-network

# ----------------------------------------------------------------
# Zookeeper and Kafka instances
# ----------------------------------------------------------------

  zoo1:
    image: zookeeper:3.4.13
    container_name: zoo1
    restart: always
    ports:
      - "2181:2181"
      - "2888"
      - "3888"
    environment:
      ZOO_MY_ID: 1
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_MAX_CLIENT_CNXNS: 60
      ZOO_STANDALONE_ENABLED: 'false'
      ZOO_SERVERS: 'server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888'

    volumes:
      - ./kafka/zoo1/data:/data
      - ./kafka/zoo1/datalog:/datalog
    networks:
      - app-network

  zoo2:
    image: zookeeper:3.4.13
    container_name: zoo2
    restart: always
    ports:
      - "2182:2181"
      - "2888"
      - "3888"
    environment:
      ZOO_MY_ID: 2
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_MAX_CLIENT_CNXNS: 60
      ZOO_STANDALONE_ENABLED: 'false'
      ZOO_SERVERS: 'server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888'
    volumes:
      - ./kafka/zoo2/data:/data
      - ./kafka/zoo2/datalog:/datalog
    networks:
      - app-network

  kafka1:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: kafka1
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: 'message:4:2'
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ZOOKEEPER_CONNECT: 'zoo1:2181,zoo2:2181'
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 4
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_LOG_DIRS: /kafka/logs
    depends_on:
      - zoo1
      - zoo2
    volumes:
      - ./kafka/broker1/kafka-logs:/kafka
      - ./kafka/broker1/logs:/logs
      - ./kafka/broker1/data:/data
    networks:
      - app-network

  kafka2:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: kafka2
    restart: always
    ports:
      - "9093:9092"
      - "9998:9998"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ZOOKEEPER_CONNECT: 'zoo1:2181,zoo2:2181'
      KAFKA_BROKER_ID: 2
      KAFKA_NUM_PARTITIONS: 4
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_LOG_DIRS: /kafka/logs
    depends_on:
      - zoo1
      - zoo2
    volumes:
      - ./kafka/broker2/kafka-logs:/kafka
      - ./kafka/broker2/logs:/logs
      - ./kafka/broker2/data:/data
    networks:
      - app-network

# ----------------------------------------------------------------
# Volumes & Networks
# ----------------------------------------------------------------
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge