services:
  # ----------------------------------------------------------------
  # Databases & Cache
  # ----------------------------------------------------------------

  # PostgreSQL with pgvector
  db_backend:
    image: pgvector/pgvector:pg16
    container_name: dev_backend_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_backend_data:/var/lib/postgresql/data
    networks:
      - app-network

  db_authorisation:
    image: postgres:16-alpine
    container_name: dev_auth_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_authorisation_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: dev_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # ----------------------------------------------------------------
  # Application Services
  # ----------------------------------------------------------------

  # Authorization Server
  authorization-server:
    build: ./backend/authorization
    container_name: dev_authorization
    ports:
      - "8083:8083"
    volumes:
      - ./backend/authorization:/app
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db_authorisation
    networks:
      - app-network

  # Core Server
  core-server:
    build: ./backend/core
    container_name: dev_core
    ports:
      - "8080:8080"
    volumes:
      - ./backend/core:/app
      - ~/.gradle:/home/gradle/.gradle
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_backend:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
    depends_on:
      - db_backend
      - redis
    networks:
      - app-network

  # Personalization Server
  personalization-server:
    build: ./backend/personalization
    container_name: dev_personalization
    ports:
      - "8082:8082"
    volumes:
      - ./backend/personalization:/app
    environment:
      - DB_HOST=db_backend
      - REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_BACKEND_URL}
      - KAFKA_CONNECTION_URL=${KAFKA_CONNECTION_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      - MINIO_RECIPES_BUCKET=${MINIO_RECIPES_BUCKET}
      - MINIO_RECIPES_OBJECT=${MINIO_RECIPES_OBJECT}
    depends_on:
      - db_backend
      - redis
      - kafka-ui
    networks:
      - app-network

  # MLPipeline
  mlpipeline:
    build: ./mlpipeline
    container_name: dev_mlpipeline
    ports:
      - "8000:8000"
    volumes:
      - ./mlpipeline:/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - db_backend
      - personalization-server
    networks:
      - app-network

  # Client: React Native Web
  client:
    build: ./client
    container_name: dev_client
    ports:
      - "8081:8081"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - API_JAVA=http://core-server:8080
      - API_GO=http://personalization-server:8082
      - API_PYTHON=http://mlpipeline:8000
    depends_on:
      - core-server
      - personalization-server
    networks:
      - app-network


# ----------------------------------------------------------------
# Kafka & Streaming
# ----------------------------------------------------------------

  kafka:
    image: bitnamilegacy/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092" # External Port
    networks:
      - app-network
    environment:
      # KRaft Basic Settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093

      # LISTENER CONFIGURATION (The Critical Part)
      # Define 3 listeners:
      #   - CONTROLLER: Internal management
      #   - EXTERNAL:   For your laptop (localhost:9092)
      #   - INTERNAL:   For Docker containers (kafka:29092)
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:29092

      # Advertise the correct address based on who is asking
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:29092

      # Map the security protocols
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT

      # Tell Kafka that internal broker communication happens on the INTERNAL listener
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

      # 3. FIX FOR "ERROR 3" (Unknown Topic)
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

    volumes:
      - kafka_data:/bitnami/kafka

  # Optional: Web UI to visualize your data
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka
    networks:
      - app-network

# ----------------------------------------------------------------
# Volumes & Networks
# ----------------------------------------------------------------
volumes:
  db_backend_data:
  db_authorisation_data:
  kafka_data:

networks:
  app-network:
    driver: bridge