[tool.poetry]
name = "mlpipeline"
version = "0.1.0"
description = ""
authors = ["sarpsahinalp <sarp.sahinalp@tum.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
